services:
  - type: web
    name: betrix-backend
    rootDir: backend
    runtime: docker
    repo: https://github.com/kushgarg132/Betrix
    plan: free
    region: oregon
    envVars:
      - key: JAVA_VERSION
        value: 17
version: "1"